ALTER TABLE ONLY users
    DROP COLUMN IF EXISTS address;
ALTER TABLE ONLY users
    DROP COLUMN IF EXISTS city;
ALTER TABLE ONLY users
    DROP COLUMN IF EXISTS region;
ALTER TABLE ONLY users
    DROP COLUMN IF EXISTS country;